---
title: "about-ena"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{about-ena}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# The European Nucleotide Archive (ENA)

[The European Nucleotide Archive (ENA)](https://www.ebi.ac.uk/ena/browser/home) is an open, supported platform for the management, sharing, integration, archiving and dissemination of sequence data.

## Database of record and platform for data management: 

ENA comprises both the globally comprehensive data resource that preserves the world’s public-domain output of sequence data (Read more about ENA Content here) and a rich portfolio of tools and services to support the management of sequence data.

## A data foundation: 

As nucleotide sequencing becomes increasingly central to applied areas such as healthcare and environmental sciences, ENA has become a foundation upon which scientific understanding of biological systems may be assembled. Our users comprise data submitters, data coordinators for sequence-based studies, direct data consumers and secondary service providers (e.g., UniProt, RNAcentral, EBI Metagenomics, Ensembl, Ensembl Genomes, ArrayExpress) that build on ENA services and content.

## Data coordination:
Our data coordination partnerships span the life sciences, covering such areas as livestock genomics, marine biotechnology, biodiversity, pathogen surveillance and stem cell biology. Within these partnerships, we support data operations variously through the provision of technology, standards, data analysis, training, support and web/API data portals. Read more here.

## Ambition:

we are committed to the utility of the ENA platform and to achieving the broadest reach and utility of sequencing technology and data.

